In [8]:
import numpy as np

# Selecting a random N between 10 and 15
N = np.random.randint(10, 15)
# 1xN dimensional vector(array)
array = np.random.random(N)

# Calculating mean of sample
mean = sum(array)/N
# Calculating variance of sample
variance = sum((array - mean)**2)/(N-1)

print(f'No. of features(N): {N}')
print(f'Vector array: {array}')
print(f'Mean of the sample: {mean}')
print(f'Variance of the sample: {variance}')

No. of features(N): 12
Vector array: [0.88131805 0.58921119 0.23600031 0.94503311 0.61764335 0.34211085
 0.58772443 0.48080785 0.86560253 0.47734499 0.75296768 0.77658082]
Mean of the sample: 0.6293620972968562
Varience of the sample: 0.049254426173079395


In [10]:
import numpy as np

# Selecting a random M between 10 and 15
M = np.random.randint(10, 15)
x = np.random.random(M)
y = np.random.random(M)

# Calculating mean of samples
x_bar = x.mean()
y_bar = y.mean()

# Calculating covarience between x and y
covariance = np.sum((x-x_bar).dot(y-y_bar))/(M-1)

print(f"No. of features(N): {N}")
print(f"Vector X: {x}")
print(f"Vector Y: {y}")
print(f"Mean of Vector X: {x_bar}")
print(f"Mean of Vector Y: {y_bar}")
print(f"Covariance: {covariance}")

Vector X: [0.76257894 0.69532736 0.80616939 0.83307544 0.8511042  0.58188547
 0.78851301 0.3557782  0.71589217 0.39446065 0.2300129  0.62847267
 0.25128063 0.56832876]
Vector Y: [0.25041994 0.64829247 0.13214953 0.72857253 0.90240148 0.746021
 0.13451796 0.78438913 0.49043383 0.70967188 0.93163715 0.76422269
 0.53599062 0.94211711]
Mean of Vector X: 0.6044914134005348
Mean of Vector Y: 0.6214883795882732
Covariance: -0.02471866940451313


In [14]:
import numpy as np

# Selecting a random N between 10 and 15
N = np.random.randint(10, 15)

# 1xN dimensional vectors(arrays)
X = np.random.random(N)
Y = np.random.random(N)

# Calculating mean of samples
X_bar = X.mean()
Y_bar = Y.mean()

# Calculating covarience between x and y
covarience = np.sum((X-X_bar).dot(Y-Y_bar)) / (N-1)
var_X = sum((X - X_bar)**2) / (N-1)
var_Y = sum((Y - Y_bar)**2) / (N-1)

# Calculating correlation
correlation = covarience/(np.sqrt(var_X * var_Y))

print(f"No. of features(N): {N}")
print(f"Vector X: {X}")
print(f"Vector Y: {Y}")
print(f"Correlation: {correlation}")

No. of features(N): 12
Vector X: [0.16377076 0.75007193 0.76567594 0.75042153 0.69794282 0.26570956
 0.15355834 0.3782113  0.00519163 0.45570036 0.51828245 0.79705103]
Vector Y: [0.24155338 0.09360154 0.23701441 0.9857868  0.85095608 0.36583296
 0.07706865 0.41000456 0.80825703 0.08032773 0.2833642  0.79941099]
Correlation: 0.22091483532869077


In [15]:
import numpy as np

M = 5  # Number of features
N = 10  # Number of samples

# Create a random matrix of shape (M, N)
matrix = np.random.rand(M, N)

# Compute the covariance matrix and correlation matrix
covariance_matrix = np.cov(matrix, rowvar=True, bias=True)
correlation_matrix = np.corrcoef(matrix)

print("Matrix (M x N):")
print(matrix)
print("\nCovariance Matrix:")
print(covariance_matrix)
print("\nCorrelation Matrix:")
print(correlation_matrix)

Matrix (M x N):
[[0.1463706  0.30922571 0.72795675 0.80720666 0.85354334 0.64869581
  0.56714699 0.31392262 0.62679097 0.16296764]
 [0.39977491 0.84669472 0.00986774 0.16523026 0.35800291 0.57750466
  0.10395155 0.63040688 0.99667827 0.20682452]
 [0.22250906 0.6920698  0.07541797 0.66047887 0.90606517 0.59767709
  0.39210673 0.31449197 0.84968011 0.8534974 ]
 [0.94195757 0.98076542 0.08691901 0.93974452 0.18039349 0.47303975
  0.11674417 0.13181438 0.74334179 0.1598135 ]
 [0.24951954 0.31614663 0.2727638  0.49545839 0.31434895 0.56526618
  0.41432907 0.46139629 0.95232613 0.52151624]]

Covariance Matrix:
[[ 0.06210085 -0.01614723  0.01153172 -0.01317773  0.00732136]
 [-0.01614723  0.09655029  0.03270357  0.05279923  0.03221219]
 [ 0.01153172  0.03270357  0.0755827   0.01715763  0.02677561]
 [-0.01317773  0.05279923  0.01715763  0.13447106  0.00894258]
 [ 0.00732136  0.03221219  0.02677561  0.00894258  0.03817264]]

Correlation Matrix:
[[ 1.         -0.20853189  0.16831943 -0.14420405  